

zuul:
  routes:
    A:
      url: http://localhost:8082
    B:
      url: http://localhost:8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

spring:
  application:
    name: zuul-app
server:
  port: 8000

